language: swift
branches:
  only:
    - master

matrix:
  include:
    - &macos
      os: osx
      osx_image: xcode11.2
      sudo: required
      language: swift

script:
  - swift test -Xswiftc -swift-version -Xswiftc 5
  - swift build --configuration release  -Xswiftc -swift-version -Xswiftc 5
