#if !canImport(ObjectiveC)
import XCTest

extension CDRCodableDecodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CDRCodableDecodingTests = [
        ("testDecodeArray", testDecodeArray),
        ("testDecodeData", testDecodeData),
        ("testDecodeDouble", testDecodeDouble),
        ("testDecodeFalse", testDecodeFalse),
        ("testDecodeFloat", testDecodeFloat),
        ("testDecodeInt", testDecodeInt),
        ("testDecodeString", testDecodeString),
        ("testDecodeTrue", testDecodeTrue),
        ("testDecodeUInt8", testDecodeUInt8),
    ]
}

extension CDRCodableEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CDRCodableEncodingTests = [
        ("testEncodeArray", testEncodeArray),
        ("testEncodeData", testEncodeData),
        ("testEncodeDouble", testEncodeDouble),
        ("testEncodeFalse", testEncodeFalse),
        ("testEncodeFloat", testEncodeFloat),
        ("testEncodeInt32", testEncodeInt32),
        ("testEncodeString", testEncodeString),
        ("testEncodeTrue", testEncodeTrue),
        ("testEncodeUInt32", testEncodeUInt32),
    ]
}

extension CDRCodablePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CDRCodablePerformanceTests = [
        ("testDataDecodeEncode", testDataDecodeEncode),
        ("testPerformanceDataDecode", testPerformanceDataDecode),
        ("testPerformanceDataEncode", testPerformanceDataEncode),
    ]
}

extension CDRCodableRoundTripTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CDRCodableRoundTripTests = [
        ("testTemp", testTemp),
        ("testTempNested", testTempNested),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CDRCodableDecodingTests.__allTests__CDRCodableDecodingTests),
        testCase(CDRCodableEncodingTests.__allTests__CDRCodableEncodingTests),
        testCase(CDRCodablePerformanceTests.__allTests__CDRCodablePerformanceTests),
        testCase(CDRCodableRoundTripTests.__allTests__CDRCodableRoundTripTests),
    ]
}
#endif
